# Generated by Django 5.0.6 on 2024-08-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nav_gest', '0001_initial'),
        ('user_gest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigner_voiture',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_gest.utilisateur'),
        ),
        migrations.AddField(
            model_name='course',
            name='id_assignation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav_gest.assigner_voiture'),
        ),
        migrations.AddField(
            model_name='embarquation',
            name='id_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav_gest.course'),
        ),
        migrations.AddField(
            model_name='embarquation',
            name='id_Etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav_gest.etudiant'),
        ),
        migrations.AddField(
            model_name='assigner_voiture',
            name='id_voiture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nav_gest.moyen_transport'),
        ),
        migrations.AlterUniqueTogether(
            name='assigner_voiture',
            unique_together={('id_user', 'id_voiture_id')},
        ),
    ]
